
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <nav style={{
            display: 'flex',
            gap: 16,
            padding: '1rem',
            borderBottom: '1px solid #eee',
            marginBottom: 24,
            alignItems: 'center',
            fontSize: 18
          }}>
            <a href="/">Home</a>
            <a href="/boards">Boards</a>
            <a href="/profile">Profile</a>
            <a href="/auth">Auth</a>
          </nav>
          {children}
        </Providers>
      </body>
    </html>
  );
}
